Repository g3w-suite/g3w-admin, pull requests merged in 2022-12, with the labels that each got.

#425 Bypass `DatasourceExits` validator for raster and vector data loaded …
  g3w-admin/qdjango/utils/validators.py
Labels: bug

#427 Fix issue #426, restore of `has_column_acl` property for embedded layers.
  g3w-admin/qdjango/utils/data.py
Labels: bug

#433 Update `paver` scripts for Ubuntu 22.04 and Python 3.10.
  pavement.py
Labels: bug, docs

#423 Apply same code style for `urls.py` and `apiurls.py` routes
  g3w-admin/OWS/urls.py
  g3w-admin/base/urls.py
  g3w-admin/client/apiurls.py
  g3w-admin/client/urls.py
  g3w-admin/core/apiurls.py
  g3w-admin/core/urls.py
  g3w-admin/editing/apiurls.py
  g3w-admin/editing/urls.py
  g3w-admin/filemanager/apiurls.py
  g3w-admin/filemanager/urls.py
  g3w-admin/openrouteservice/apiurls.py
  g3w-admin/openrouteservice/urls.py
  g3w-admin/qdjango/apiurls.py
  g3w-admin/qdjango/urls.py
  g3w-admin/qplotly/apiurls.py
  g3w-admin/qplotly/urls.py
  g3w-admin/usersmanage/urls.py
Labels: refactoring
