Repository g3w-suite/g3w-admin, pull requests merged in 2023-11, with the labels that each got.

#639 Bump version from `(0, 0, 0, 'unstable', 0)` to `(3, 7, 0, 'unstable', 0)`
  g3w-admin/base/__init__.py
Labels: config

#638 :sparkles: Add users management inside the Users Group form
  g3w-admin/base/urls.py
  g3w-admin/qdjango/migrations/0114_alter_sessiontokenfilter_token.py
  g3w-admin/qdjango/models/filters.py
  g3w-admin/qdjango/tests/data/geodata/qgis_widget_test_data.gpkg
  g3w-admin/qdjango/tests/test_api.py
  g3w-admin/usersmanage/api/filters.py
  g3w-admin/usersmanage/api/permissions.py
  g3w-admin/usersmanage/api/serializers.py
  g3w-admin/usersmanage/api/views.py
  g3w-admin/usersmanage/apiurls.py
  g3w-admin/usersmanage/forms.py
  g3w-admin/usersmanage/templates/usersmanage/user_group_form.html
  g3w-admin/usersmanage/tests/test_api.py
  g3w-admin/usersmanage/tests/test_forms.py
  g3w-admin/usersmanage/views.py
Labels: feature

#644 ⬆️ Bump g3w-client from 3.8.13 to 3.8.14
  README.md
  g3w-admin/client/static/client/js/app.min.js
Labels: dependencies

#631 :sparkles: Add search and editing support for `Relation Reference` widget (1:N relations)
  g3w-admin/client/static/client/js/app.min.js
  g3w-admin/core/api/base/views.py
  g3w-admin/editing/static/editing/js/plugin.js
  g3w-admin/editing/tests/test_api_transaction_group.py
  g3w-admin/qdjango/api/projects/serializers.py
  g3w-admin/qdjango/static/qdjango/js/widget.js
  g3w-admin/qdjango/tests/base.py
  g3w-admin/qdjango/tests/data/g3wsuite_project_test_qgis328.qgs
  g3w-admin/qdjango/tests/data/geodata/qgis_widget_test_data.gpkg
  g3w-admin/qdjango/tests/test_api.py
  g3w-admin/qdjango/utils/data.py
  g3w-admin/qdjango/utils/edittype.py
Labels: feature

#647 ⬆️ Bump g3w-client from 3.8.14 to 3.8.15
  README.md
  g3w-admin/client/static/client/js/app.min.js
  g3w-admin/client/static/client/js/vendor.min.js
Labels: dependencies

#650 :sparkles: Change password at first login
  g3w-admin/base/settings/base.py
  g3w-admin/base/settings/tests_settings.py
  g3w-admin/base/urls.py
  g3w-admin/usersmanage/forms.py
  g3w-admin/usersmanage/migrations/0014_userdata_change_password_first_login.py
  g3w-admin/usersmanage/models.py
  g3w-admin/usersmanage/tests/test_views.py
  g3w-admin/usersmanage/views.py
Labels: feature

#652 :sparkles: Add support to qgis `'postgresraster'` layer
  g3w-admin/client/static/client/js/app.min.js
  g3w-admin/qdjango/migrations/0115_alter_layer_layer_type.py
  g3w-admin/qdjango/models/projects.py
  g3w-admin/qdjango/templates/qdjango/include/layer_icon.html
Labels: feature

#657 Fix crs for layers in `G3W_PROJ4_EPSG` setting
  g3w-admin/qdjango/api/projects/serializers.py
Labels: bug, backport_v3.6

#660 Delete old QGIS project file on update.
  g3w-admin/qdjango/receivers.py
Labels: feature

#601 :recycle: Refactor REST API response for: `/interface/ows`
  g3w-admin/client/static/client/css/app.min.css
  g3w-admin/client/static/client/js/app.min.js
  g3w-admin/core/api/views.py
  g3w-admin/core/tests/test_api.py
Labels: refactoring

#655 add the undocumented WEBP image format
  g3w-admin/qdjango/migrations/0109_project_wms_getmap_format.py
  g3w-admin/qdjango/models/projects.py
Labels: feature

#666 :bug: Add check for anonymous user in LayerAclAccessControFilter
  g3w-admin/qdjango/server_filters/accesscontrol/layer_acl.py
Labels: bug

#667 ⬆️ Bump g3w-client-plugin-editing from 3.6.6 to 3.6.7
  g3w-admin/editing/static/editing/js/plugin.js
Labels: dependencies

#658 Fix crs property of layer in /api/config API REST.
  g3w-admin/qdjango/api/projects/serializers.py
Labels: bug

#646 :sparkles: Add new geocoding provider: Bing
  g3w-admin/base/settings/base_geo_settings.py
  g3w-admin/client/static/client/css/app.min.css
  g3w-admin/client/static/client/geocoding-providers/bing_places.js
  g3w-admin/client/static/client/geocoding-providers/bing_streets.js
  g3w-admin/client/static/client/geocoding-providers/google.js
  g3w-admin/client/static/client/geocoding-providers/nominatim.js
  g3w-admin/client/static/client/images/pushpin.svg
  g3w-admin/client/static/client/js/app.min.js
  g3w-admin/client/tests/test_api.py
  g3w-admin/core/api/serializers.py
  g3w-admin/editing/static/editing/js/plugin.js
  g3w-admin/qdjango/forms/projects.py
  g3w-admin/qdjango/migrations/0115_project_geocoding_providers.py
  g3w-admin/qdjango/models/projects.py
  g3w-admin/qdjango/utils/models.py
  g3w-admin/qdjango/views/projects.py
Labels: feature

#669 :sparkles: Multilayer editing capability activation
  g3w-admin/core/signals.py
  g3w-admin/core/static/css/g3wadmin.css
  g3w-admin/core/static/dist/css/g3wadmin.min.css
  g3w-admin/core/templatetags/g3wadmin_tags.py
  g3w-admin/editing/forms.py
  g3w-admin/editing/receivers.py
  g3w-admin/editing/static/editing/js/widget.js
  g3w-admin/editing/templates/editing/editing_layer_active_form.html
  g3w-admin/editing/templates/editing/project_layers_action.html
  g3w-admin/editing/tests/test_api.py
  g3w-admin/editing/tests/test_views.py
  g3w-admin/editing/urls.py
  g3w-admin/editing/views.py
  g3w-admin/qdjango/api/layers/serializers.py
  g3w-admin/qdjango/api/layers/views.py
  g3w-admin/qdjango/apiurls.py
  g3w-admin/qdjango/templates/qdjango/layers_list.html
Labels: feature, editing

#675 Mispelled word: `datasoruce` → `datasource`
  g3w-admin/qdjango/locale/it/LC_MESSAGES/django.po
  g3w-admin/qdjango/templates/qdjango/ajax/layer_detail.html
  g3w-admin/qdjango/utils/models.py
  g3w-admin/qdjango/utils/structure.py
Labels: i18n

#627 :sparkles: Add new project option: `WMS GetMap image format`
  g3w-admin/client/static/client/css/app.min.css
  g3w-admin/qdjango/api/projects/serializers.py
  g3w-admin/qdjango/forms/projects.py
  g3w-admin/qdjango/migrations/0109_project_wms_getmap_format.py
  g3w-admin/qdjango/migrations/0110_sessiontokenfilterlayer_name.py
  g3w-admin/qdjango/models/projects.py
  g3w-admin/qdjango/tests/test_embedded_layers.py
  g3w-admin/qdjango/tests/test_forms.py
Labels: feature

#676 Performance
  g3w-admin/base/settings/base.py
  g3w-admin/base/settings/tests_settings.py
  g3w-admin/caching/receivers.py
  g3w-admin/client/api/views.py
  g3w-admin/client/tests/test_api.py
  g3w-admin/core/receivers.py
  g3w-admin/core/tests/base.py
  g3w-admin/core/utils/decorators.py
  g3w-admin/editing/receivers.py
  g3w-admin/qdjango/api/projects/serializers.py
  g3w-admin/qdjango/models/projects.py
  g3w-admin/qdjango/receivers.py
  g3w-admin/qdjango/tests/test_api.py
  g3w-admin/qdjango/views/projects.py
  g3w-admin/qplotly/receivers.py
Labels: feature

#678 :bug: Fix missing `: . = ,` in `qdjango-prjtheme-api` url.
  g3w-admin/qdjango/apiurls.py
  g3w-admin/qdjango/tests/test_theme.py
Labels: bug
