Repository g3w-suite/g3w-admin, pull requests merged in 2023-05, with the labels that each got.

#540 Fix missing breadcrumbs on `qdjango` app
  g3w-admin/base/settings/base.py
  g3w-admin/core/sitetrees.py
  g3w-admin/filemanager/sitetrees.py
  g3w-admin/openrouteservice/sitetrees.py
  g3w-admin/qdjango/sitetrees.py
  g3w-admin/qdjango/urls.py
  g3w-admin/usersmanage/sitetrees.py
  requirements.txt
Labels: bug

#541 Fix undefined `$dataTable` variable within `g3wadmin/ui.js`
  g3w-admin/core/static/js/g3wadmin/ui.js
Labels: refactoring

#544 Fix upload `.qgz` project file
  g3w-admin/core/forms.py
  g3w-admin/core/views.py
  g3w-admin/qdjango/forms/projects.py
  g3w-admin/qdjango/mixins/views.py
  g3w-admin/qdjango/tests/data/test_qgz_project_328.qgz
  g3w-admin/qdjango/tests/test_forms.py
  g3w-admin/qdjango/tests/utils.py
  requirements.txt
Labels: bug

#547 Refactor `"qdjango.apps"` logger
  g3w-admin/qdjango/apps.py
Labels: refactoring

#514 Update pace.js library to version 1.2.4.
  g3w-admin/templates/base.html
  package.json
  yarn.lock
Labels: dependencies

#551 Messages translation
  g3w-admin/core/forms.py
  g3w-admin/core/static/css/g3wadmin.css
  g3w-admin/qdjango/api/projects/serializers.py
  g3w-admin/qdjango/forms/messages.py
  g3w-admin/qdjango/forms/projects.py
  g3w-admin/qdjango/migrations/0107_auto_20230516_0806.py
  g3w-admin/qdjango/templates/qdjango/message/list.html
  g3w-admin/qdjango/translation.py
Labels: feature

#556 Restore bind on actions layers trigger on Layers list page.
  .gitignore
  g3w-admin/caching/templates/caching/layer_action.html
  g3w-admin/core/static/css/g3wadmin.css
  g3w-admin/core/static/dist/css/g3wadmin.min.css
  g3w-admin/core/static/dist/js/g3wadmin.min.js
  g3w-admin/core/static/js/g3wadmin/ui.js
  g3w-admin/editing/templates/editing/layer_action.html
  g3w-admin/qdjango/static/qdjango/js/widget.js
  g3w-admin/qdjango/templates/qdjango/layer_actions/filter_by_user.html
  g3w-admin/qdjango/templates/qdjango/layers_list.html
  g3w-admin/qplotly/templates/qplotly/layer_action.html
Labels: bug
