Repository g3w-suite/g3w-admin, pull requests merged in 2023-10, with the labels that each got.

#614 :bug: Fix more than one geometry field on editing update.
  g3w-admin/editing/api/base/views.py
Labels: bug

#617 ⬆️ Bump g3w-client from 3.8.10 to 3.8.11 by @volterra79
  README.md
  g3w-admin/client/static/client/js/app.min.js
Labels: dependencies

#615 Backport: #614 - Layer feature with more than one geometry field fail on editing update
  g3w-admin/editing/api/base/views.py
Labels: bug

#621 :bug: Fix subset filter constraints for Anonymous user
  g3w-admin/qdjango/models/constraints.py
  g3w-admin/qdjango/tests/test_constraints.py
Labels: bug

#625 Backport: #621- Fix subset filter constraints for Anonymous user
  g3w-admin/qdjango/models/constraints.py
Labels: bug

#630 ⬆️ Bump g3w-client from 3.8.11 to 3.8.12
  README.md
  g3w-admin/client/static/client/js/app.min.js
Labels: dependencies

#632 :bug: Fix issue #629
  g3w-admin/base/__init__.py
  g3w-admin/editing/views.py
Labels: bug

#623 :sparkles: Allow to store layer's expression filters (authenticathed users)
  g3w-admin/client/static/client/css/app.min.css
  g3w-admin/client/static/client/js/app.min.js
  g3w-admin/editing/static/editing/js/plugin.js
  g3w-admin/qdjango/admin.py
  g3w-admin/qdjango/api/layers/serializers.py
  g3w-admin/qdjango/api/projects/serializers.py
  g3w-admin/qdjango/migrations/0109_filterlayersaved.py
  g3w-admin/qdjango/migrations/0110_sessiontokenfilterlayer_name.py
  g3w-admin/qdjango/migrations/0111_alter_sessiontokenfilterlayer_name.py
  g3w-admin/qdjango/migrations/0112_auto_20231017_0752.py
  g3w-admin/qdjango/migrations/0113_auto_20231019_1237.py
  g3w-admin/qdjango/models/filters.py
  g3w-admin/qdjango/tests/data/geodata/qgis_widget_test_data.gpkg
  g3w-admin/qdjango/tests/test_api.py
  g3w-admin/qdjango/vector.py
Labels: feature
