Repository g3w-suite/g3w-admin, pull requests merged in 2023-01, with the labels that each got.

#438 Refactoring settings parameter for custom CRS management.
  g3w-admin/base/settings/base_geo_settings.py
  g3w-admin/core/api/serializers.py
  g3w-admin/core/api/views.py
  g3w-admin/qdjango/api/projects/serializers.py
  pavement.py
Labels: bug, refactoring

#430 Get max extent CRS from QGIS API.
  g3w-admin/caching/tests/test_views.py
  g3w-admin/caching/views.py
  g3w-admin/client/tests/test_api.py
  g3w-admin/core/api/serializers.py
  g3w-admin/core/api/views.py
  g3w-admin/core/apiurls.py
  g3w-admin/core/tests/test_api.py
  g3w-admin/core/utils/geo.py
  g3w-admin/qdjango/api/projects/serializers.py
Labels: enhancement

#442 Fix ORS issue with raster layers
  g3w-admin/openrouteservice/utils.py
Labels: bug

#440 Delete `.readthedocs.yml`
  .readthedocs.yml
Labels: config

#444 Fix bug in ORS with interval range in minutes
  g3w-admin/openrouteservice/api/views.py
Labels: bug

#447 Add Temporal step ad unit properties
  g3w-admin/qdjango/tests/test_api.py
  g3w-admin/qdjango/utils/data.py
  g3w-admin/qtimeseries/static/qtimeseries/js/plugin.js
  g3w-admin/templates/rest_framework/api.html
Labels: feature
