Repository g3w-suite/g3w-admin, pull requests merged in 2023-09, with the labels that each got.

#594 Give to Editor Level 1 user upload geo-data grant
  g3w-admin/filemanager/apps.py
  g3w-admin/filemanager/receivers.py
  g3w-admin/filemanager/tests/test_api.py
  g3w-admin/filemanager/tests/test_views.py
  g3w-admin/filemanager/views.py
  g3w-admin/qdjango/tests/data/value_relation_qgis328.qgs
  g3w-admin/templates/include/navbar_right_menu.html
  g3w-admin/templates/include/sidebar_right.html
  g3w-admin/usersmanage/tests/test_forms.py
Labels: feature

#596 Relation type `many` with multifield keys
  g3w-admin/client/static/client/js/app.min.js
  g3w-admin/core/tests/test_api.py
  g3w-admin/editing/api/base/views.py
  g3w-admin/editing/static/editing/js/plugin.js
  g3w-admin/qdjango/tests/test_utils.py
  g3w-admin/qdjango/utils/data.py
  g3w-admin/qdjango/vector.py
Labels: bug, feature

#602 ⬆️ Bump g3w-client from 3.8.9 to 3.8.10. ⬆️ Bump g3w-client-plugin-editing from 3.6.4 to 3.6.5
  README.md
  g3w-admin/client/static/client/js/app.min.js
  g3w-admin/client/static/client/js/vendor.min.js
  g3w-admin/editing/static/editing/js/plugin.js
Labels: dependencies

#605 ⬆️ Bump g3w-client-plugin-editing from 3.6.5 to 3.6.6 by @volterra79
  g3w-admin/editing/static/editing/js/plugin.js
Labels: dependencies

#606 Fix issue 603
  g3w-admin/caching/tests/test_api.py
  g3w-admin/qdjango/auth.py
  g3w-admin/qdjango/server_filters/accesscontrol/layer_acl.py
  g3w-admin/qdjango/tests/data/geodata/qgis_widget_test_data.gpkg
  g3w-admin/qdjango/tests/test_constraints.py
  g3w-admin/qdjango/tests/test_ows.py
Labels: bug
