Repository g3w-suite/g3w-admin, pull requests merged in 2023-04, with the labels that each got.

#517 Add 'mode' `featurecount` to vector REST API
  g3w-admin/core/api/base/views.py
  g3w-admin/core/apiurls.py
  g3w-admin/core/utils/qgisapi.py
  g3w-admin/qdjango/api/projects/serializers.py
  g3w-admin/qdjango/api/projects/views.py
  g3w-admin/qdjango/tests/base.py
  g3w-admin/qdjango/tests/data/project_themes_qgis328.qgs
  g3w-admin/qdjango/tests/test_theme.py
  g3w-admin/qdjango/vector.py
Labels: feature

#520 Manage WMS services without `GetFeatureInfo` request.
  g3w-admin/core/api/views.py
Labels: bug

#525 Fix check locked features on delete editing action
  g3w-admin/editing/api/base/views.py
Labels: bug

#509 Set a default fallback image as Group header logo image on save (ref: `CLIENT_G3WSUITE_LOGO`)
  g3w-admin/core/apps.py
  g3w-admin/core/forms.py
  g3w-admin/core/migrations/0081_auto_20230329_0739.py
  g3w-admin/core/models.py
  g3w-admin/core/templates/core/group_list.html
  g3w-admin/core/views.py
Labels: ux

#512 Create a project's messaging system.
  g3w-admin/core/sitetrees.py
  g3w-admin/qdjango/admin.py
  g3w-admin/qdjango/api/projects/serializers.py
  g3w-admin/qdjango/forms/__init__.py
  g3w-admin/qdjango/forms/messages.py
  g3w-admin/qdjango/forms/projects.py
  g3w-admin/qdjango/migrations/0105_message.py
  g3w-admin/qdjango/migrations/0106_message_order.py
  g3w-admin/qdjango/models/__init__.py
  g3w-admin/qdjango/models/messages.py
  g3w-admin/qdjango/models/projects.py
  g3w-admin/qdjango/sitetrees.py
  g3w-admin/qdjango/templates/qdjango/message/form.html
  g3w-admin/qdjango/templates/qdjango/message/list.html
  g3w-admin/qdjango/templates/qdjango/project_list.html
  g3w-admin/qdjango/tests/test_messages.py
  g3w-admin/qdjango/urls.py
  g3w-admin/qdjango/views/__init__.py
  g3w-admin/qdjango/views/messages.py
  g3w-admin/qdjango/views/projects.py
Labels: feature

#529 Fix missing date from and date to messages checking.
  g3w-admin/qdjango/api/projects/serializers.py
  g3w-admin/qdjango/templates/qdjango/message/list.html
  g3w-admin/qdjango/templatetags/qdjango_tags.py
  g3w-admin/qdjango/tests/test_messages.py
Labels: feature

#528 Prevent applying i18n on static assets URLs when `DEBUG = true`
  g3w-admin/base/urls.py
Labels: refactoring

#473 Clear code and libraries
  g3w-admin/core/static/dist/css/vendor.min.css
  g3w-admin/core/static/dist/js/vendor.min.js
  g3w-admin/core/static/js/g3wadmin/main.js
  g3w-admin/templates/base.html
  package.json
Labels: refactoring

#532 Add QGIS version within compatibility table and update `venv` installation instructions (ref: `README.md`)
  README.md
Labels: docs

#522 Expression eval API: reproject form feature if srid qgis project != from layer srid.
  g3w-admin/core/utils/qgisapi.py
Labels: bug

#537 Update `"@bower_components/bootstrap-datepicker"` to v1.9.0
  g3w-admin/core/static/js/g3wadmin.js
  g3w-admin/core/static/js/g3wadmin/forms.js
  g3w-admin/core/static/js/g3wadmin/main.js
  g3w-admin/core/static/js/g3wadmin/tpl.js
  g3w-admin/core/static/js/g3wadmin/ui.js
  g3w-admin/core/static/js/g3wadmin/utils.js
  g3w-admin/core/static/js/g3wadmin/widget.js
  g3w-admin/qdjango/templates/qdjango/layers_list.html
  g3w-admin/templates/base.html
  package.json
  yarn.lock
Labels: dependencies, i18n

#531 Generate a unique `SECRET_KEY_FILE` when deploying a new django instance (ref: `build_suite.sh`)
  .gitignore
  ci_scripts/build_suite.sh
  ci_scripts/setup_suite.sh
  g3w-admin/base/management/commands/generate_secret_key_file.py
  g3w-admin/base/settings/base.py
  g3w-admin/core/utils/decorators.py
  g3w-admin/core/views.py
  g3w-admin/qdjango/views/projects.py
Labels: config
