Repository g3w-suite/g3w-admin, pull requests merged in 2024-08, with the labels that each got.

#921 Fix explode_expression
  g3w-admin/qdjango/tests/test_utils.py
  g3w-admin/qdjango/utils/qgis.py
Labels: bug, backport to v.3.7.x, backport to v.3.8.x

#925 Update French Translation
  g3w-admin/locale/fr/LC_MESSAGES/django.mo
  g3w-admin/locale/fr/LC_MESSAGES/django.po
  g3w-admin/locale/fr/LC_MESSAGES/djangojs.mo
  g3w-admin/locale/fr/LC_MESSAGES/djangojs.po
Labels: i18n, backport to v.3.8.x

#924 :arrow_up: Bump g3w-client v3.10.1, g3w-client-plugin-editing v3.8.1
  README.md
  g3w-admin/client/static/client/css/app.min.css
  g3w-admin/client/static/client/js/app.min.js
  g3w-admin/client/static/client/js/app.min.js.map
  g3w-admin/editing/static/editing/js/plugin.js
Labels: dependencies

#927 ⬆️ Bump g3w-client v3.10.2, g3w-client-plugin-editing v3.8.2
  README.md
  g3w-admin/client/static/client/js/app.min.js
  g3w-admin/client/static/client/js/app.min.js.map
  g3w-admin/client/static/client/js/vendor.min.js
  g3w-admin/editing/static/editing/js/plugin.js
Labels: dependencies
