Repository g3w-suite/g3w-admin, pull requests merged in 2024-06, with the labels that each got.

#871 Update name, origname, qgs_layer_id model Layer fields to max_length
  g3w-admin/qdjango/migrations/0122_auto_20240604_1515.py
  g3w-admin/qdjango/models/projects.py
Labels: bug

#876 Fix field filter for comma separated values ​​requests (e.g. `"field" IN('value1', 'value2')`).
  g3w-admin/core/api/filters.py
  g3w-admin/qdjango/tests/data/geodata/qgis_widget_test_data.gpkg
  g3w-admin/qdjango/tests/test_api.py
Labels: bug, backport to v.3.7.x

#877 Fix for 'comma' inside value of a field filter. (#876)
  g3w-admin/core/api/filters.py
  g3w-admin/qdjango/tests/test_api.py
Labels: bug

#869 Client loadlayer url errorl setting
  g3w-admin/base/settings/base.py
  g3w-admin/qdjango/api/projects/serializers.py
Labels: feature

#879 Replace `wait-for-it` with `pg_isready` within `setup_suite.sh`
  ci_scripts/setup_suite.sh
Labels: config
