Repository g3w-suite/g3w-admin, pull requests merged in 2024-11, with the labels that each got.

#971 Fix `SameSite` cookie property on file download response
  g3w-admin/qdjango/vector.py
Labels: bug

#978 Update weasyprint to version 63.0
  requirements.txt
Labels: dependencies, backport to v.3.8.x

#980 Filter fields by user on response of /api/vector/data
  g3w-admin/core/api/base/views.py
  g3w-admin/qdjango/tests/test_column_acl.py
Labels: bug, feature, backport to v.3.8.x

#970 :arrow_up:Bump g3w-client v3.10.5 and g3w-client-plugin-editing v3.8.4
  README.md
  g3w-admin/client/static/client/js/app.min.js
  g3w-admin/client/static/client/js/app.min.js.map
  g3w-admin/editing/static/editing/js/plugin.js
Labels: dependencies

#982 ⬆️Bump g3w-client v3.9.11
  README.md
  g3w-admin/client/static/client/js/app.min.js
  g3w-admin/client/static/client/js/app.min.js.map
  g3w-admin/client/static/client/js/vendor.min.js
Labels: dependencies
