Repository g3w-suite/g3w-admin, pull requests merged in 2024-03, with the labels that each got.

#769 Patch for QgsXmlUltils.
  g3w-admin/qplotly/vendor/DataPlotly/core/plot_settings.py
Labels: bug, backport to v.3.7.x

#761 Add `macrogroup_id` to group serializer.
  g3w-admin/about/api/filters.py
  g3w-admin/about/tests/test_api.py
  g3w-admin/client/static/client/js/app.min.js
  g3w-admin/core/api/serializers.py
  g3w-admin/editing/static/editing/js/plugin.js
Labels: feature, backport to v.3.7.x, backport to v.3.6.x

#768 Fix registration template issues.
  g3w-admin/usersmanage/locale/it/LC_MESSAGES/django.mo
  g3w-admin/usersmanage/locale/it/LC_MESSAGES/django.po
  g3w-admin/usersmanage/templates/django_registration/activation_failed.html
Labels: bug, backport to v.3.7.x

#776 Add 'opacity' property.
  g3w-admin/qdjango/api/projects/serializers.py
Labels: bug, backport to v.3.7.x

#782 ⬆️ Bump g3w-client v3.9.5
  g3w-admin/client/static/client/js/app.min.js
Labels: dependencies

#790 Fix invalidating project cache on link/unlink search widget.
  g3w-admin/qdjango/views/projects.py
Labels: bug, backport to v.3.7.x

#796 ACL Filter layer widget on vector download as shp, gpkg, gpx, xls, csv etc.
  g3w-admin/qdjango/tests/test_column_acl.py
  g3w-admin/qdjango/vector.py
Labels: bug, backport to v.3.7.x
