Repository g3w-suite/g3w-admin, pull requests merged in 2024-04, with the labels that each got.

#797 ⬆️ Bump g3w-client v3.9.6, g3w-client-plugin-editing v3.7.7, g3w-client-plugin-openrouteservice v3.7.1
  g3w-admin/client/static/client/images/mapcentermarker.svg
  g3w-admin/client/static/client/js/app.min.js
  g3w-admin/editing/static/editing/js/plugin.js
  g3w-admin/openrouteservice/static/openrouteservice/js/plugin.js
Labels: dependencies

#801 ⬆️ Bump g3w-client-plugin-editing v3.7.8
  g3w-admin/editing/static/editing/js/plugin.js
Labels: dependencies

#804 :bug: Fix 'formatter' parameter in POST requests
  g3w-admin/core/api/filters.py
Labels: bug, backport to v.3.7.x

#807 Ordering by `fformatter` field.
  g3w-admin/core/api/base/views.py
Labels: feature

#816 Fix Geos Polygon instance for Geoconstraint
  g3w-admin/editing/receivers.py
Labels: bug, backport to v.3.7.x

#819 Remove wms restricted layouts.
  g3w-admin/qdjango/utils/data.py
Labels: bug, backport to v.3.7.x

#787 Internal components refactor [g3w-client #574]
  g3w-admin/base/settings/base.py
  g3w-admin/client/static/client/js/app.min.js
  g3w-admin/client/static/client/js/app.min.js.map
  g3w-admin/client/tests/test_api.py
  g3w-admin/editing/static/editing/js/plugin.js
  g3w-admin/qdjango/api/projects/serializers.py
Labels: refactoring

#828 Fix printing Atals layouts without Map items
  g3w-admin/qdjango/server_services/vendors/threeliz/core.py
Labels: bug, backport to v.3.7.x

#793 🐛 Fix `SameSite` cookie property.
  g3w-admin/client/views.py
Labels: bug, backport to v.3.7.x
