Repository g3w-suite/g3w-admin, pull requests merged in 2024-07, with the labels that each got.

#887 Feature count refresh
  ci_scripts/Dockerfile.deps
  ci_scripts/Dockerfile.ltr.deps
  docker-compose.latest.yml
  docker-compose.ltr.yml
  g3w-admin/editing/api/base/views.py
  g3w-admin/qdjango/tests/test_utils.py
  run_docker_tests.sh
Labels: bug, backport to v.3.7.x, backport to v.3.8.x

#894 Feature count refresh (#887)
  ci_scripts/Dockerfile.deps
  ci_scripts/Dockerfile.ltr.deps
  docker-compose.latest.yml
  docker-compose.ltr.yml
  g3w-admin/editing/api/base/views.py
  g3w-admin/qdjango/tests/test_utils.py
  run_docker_tests.sh
Labels: bug

#888 ⬆️ Bump g3w-client v3.9.10, g3w-client-plugin-editing v3.7.9
  README.md
  g3w-admin/client/static/client/js/app.min.js
  g3w-admin/editing/static/editing/js/plugin.js
Labels: dependencies

#895 ⬆️ Bump g3w-client v3.9.10
  README.md
  g3w-admin/client/static/client/js/app.min.js
  g3w-admin/editing/static/editing/js/plugin.js
Labels: bug

#905 Fix check user is a superuser
  g3w-admin/usersmanage/api/permissions.py
Labels: bug, backport to v.3.7.x, backport to v.3.8.x

#898 feat - use environment variable for superuser admin and password
  ci_scripts/setup_suite.sh
Labels: feature

#911 Add 'target' attribute to the Bleach allowed attributes
  g3w-admin/base/settings/base.py
Labels: bug, backport to v.3.7.x, backport to v.3.8.x

#881 Allow to create projects from CLI
  g3w-admin/base/management/commands/load_project.py
  g3w-admin/base/management/commands/reload_demo.py
Labels: feature
