Repository g3w-suite/g3w-admin, pull requests merged in 2024-12, with the labels that each got.

#983 ⬆️Bump g3w-client v3.10.6
  g3w-admin/client/static/client/js/app.min.js
  g3w-admin/client/static/client/js/app.min.js.map
Labels: dependencies

#985 Refactoring auth check order for OGC Service
  g3w-admin/qdjango/auth.py
  g3w-admin/qdjango/tests/data/geodata/qgis_widget_test_data.gpkg
  g3w-admin/qdjango/tests/test_ows.py
Labels: bug, backport to v.3.8.x

#987 ⬆️Bump g3w-client v3.10.6
  README.md
  g3w-admin/client/static/client/js/app.min.js
  g3w-admin/client/static/client/js/app.min.js.map
Labels: dependencies

#989 Refactoring auth check order (#985)
  g3w-admin/qdjango/auth.py
  g3w-admin/qdjango/tests/test_ows.py
Labels: bug

#990 Eval expression response json
  g3w-admin/core/api/views.py
  g3w-admin/core/tests/test_qgisapi.py
Labels: refactoring

#994 Add social account login capability
  g3w-admin/base/settings/base.py
  g3w-admin/base/settings/local_settings_example.py
  g3w-admin/base/urls.py
  g3w-admin/templates/login.html
  g3w-admin/usersmanage/receivers.py
  g3w-admin/usersmanage/templates/socialaccount/provider_list.html
  g3w-admin/usersmanage/vendors/__init__.py
  g3w-admin/usersmanage/vendors/allauth/__init__.py
  g3w-admin/usersmanage/vendors/allauth/adapter.py
  requirements.txt
Labels: feature, backport to v.3.8.x

#997 Fix PyQt object translate for Qplotly
  g3w-admin/qplotly/utils/qplotly_factory.py
Labels: bug, backport to v.3.8.x

#1001 Add management for setting SOCIALACCOUNT_USER_GROUP
  g3w-admin/usersmanage/vendors/allauth/adapter.py
Labels: feature, backport to v.3.8.x

#1000 Fix media update
  g3w-admin/core/utils/vector.py
Labels: bug, backport to v.3.8.x

#993 :arrow_up: Client v3.10.7
  README.md
  g3w-admin/client/static/client/js/app.min.js
  g3w-admin/client/static/client/js/app.min.js.map
Labels: dependencies
