Repository g3w-suite/g3w-admin, pull requests merged in 2024-09, with the labels that each got.

#933 Field default value when they are 0' or 'False'
  g3w-admin/core/utils/structure.py
Labels: bug, backport to v.3.8.x

#937 Fix ordering expression
  g3w-admin/core/api/filters.py
Labels: backport to v.3.7.x, backport to v.3.6.x, backport to v.3.8.x

#934 ⬆️ Bump g3w-client v3.10.3, g3w-client-plugin-editing v3.8.3
  README.md
  g3w-admin/client/static/client/js/app.min.js
  g3w-admin/client/static/client/js/app.min.js.map
  g3w-admin/editing/static/editing/js/plugin.js
  g3w-admin/editing/static/editing/js/plugin.js.map
  g3w-admin/editing/static/editing/js/src/plugins/editing/plugin.js.map
Labels: dependencies
