Repository g3w-suite/g3w-admin, pull requests merged in 2024-02, with the labels that each got.

#724 ⬆️ Bump g3w-client v3.8.16 and g3w-client-plugin-editing v3.6.8
  README.md
  g3w-admin/client/static/client/js/app.min.js
  g3w-admin/client/static/client/js/vendor.min.js
  g3w-admin/editing/static/editing/js/plugin.js
Labels: bug, dependencies

#726 Fix for geocoding mapcontrol.
  g3w-admin/client/tests/test_api.py
  g3w-admin/core/api/serializers.py
Labels: bug, backport to v.3.7.x

#732 Editing copy feature media fix
  g3w-admin/core/utils/vector.py
  g3w-admin/editing/api/base/views.py
  g3w-admin/editing/api/views.py
Labels: bug, backport to v.3.7.x

#730 Fix language issue
  g3w-admin/core/static/dist/js/g3wadmin.min.js
  g3w-admin/core/static/js/g3wadmin/ui.js
Labels: bug, backport to v.3.7.x

#734 :bug: Fix for editing geometry fields as property.
  g3w-admin/core/utils/structure.py
Labels: bug, backport to v.3.7.x

#737 Update django version to 3.2.24.
  requirements.txt
Labels: python, backport to v.3.7.x

#741 Rename django.contrib.messages in django_messages.
  g3w-admin/qdjango/admin.py
Labels: bug, backport to v.3.7.x

#744 Replace ugettext with gettext: RemovedInDjango40Warning
  g3w-admin/OWS/utils/data.py
  g3w-admin/caching/forms.py
  g3w-admin/core/admin.py
  g3w-admin/core/api/base/views.py
  g3w-admin/core/api/views.py
  g3w-admin/core/configs.py
  g3w-admin/core/forms.py
  g3w-admin/core/models.py
  g3w-admin/core/utils/data.py
  g3w-admin/core/utils/forms.py
  g3w-admin/core/utils/qgisapi.py
  g3w-admin/core/utils/structure.py
  g3w-admin/editing/api/base/views.py
  g3w-admin/editing/forms.py
  g3w-admin/editing/receivers.py
  g3w-admin/openrouteservice/api/views.py
  g3w-admin/openrouteservice/forms.py
  g3w-admin/openrouteservice/utils.py
  g3w-admin/qdjango/api/layers/views.py
  g3w-admin/qdjango/api/projects/serializers.py
  g3w-admin/qdjango/forms/messages.py
  g3w-admin/qdjango/forms/projects.py
  g3w-admin/qdjango/models/column_acl.py
  g3w-admin/qdjango/models/constraints.py
  g3w-admin/qdjango/models/geoconstraints.py
  g3w-admin/qdjango/models/messages.py
  g3w-admin/qdjango/models/projects.py
  g3w-admin/qdjango/models/qgisauth.py
  g3w-admin/qdjango/utils/data.py
  g3w-admin/qdjango/utils/exceptions.py
  g3w-admin/qdjango/utils/validators.py
  g3w-admin/qplotly/api/widgets/serializers.py
  g3w-admin/qplotly/models.py
  g3w-admin/qtimeseries/forms.py
  g3w-admin/usersmanage/forms.py
  g3w-admin/usersmanage/models.py
  g3w-admin/usersmanage/utils.py
  g3w-admin/usersmanage/views.py
Labels: refactoring, backport to v.3.7.x

#743 ⬆️ Bump g3w-client v3.9.3 and g3w-client-plugin-editing v3.7.4
  g3w-admin/client/static/client/js/app.min.js
  g3w-admin/editing/static/editing/js/plugin.js
Labels: dependencies

#745 Replace ugettext with gettext: RemovedInDjango40Warning (#744)
  g3w-admin/OWS/utils/data.py
  g3w-admin/caching/forms.py
  g3w-admin/core/admin.py
  g3w-admin/core/api/base/views.py
  g3w-admin/core/api/views.py
  g3w-admin/core/configs.py
  g3w-admin/core/forms.py
  g3w-admin/core/models.py
  g3w-admin/core/utils/data.py
  g3w-admin/core/utils/forms.py
  g3w-admin/core/utils/qgisapi.py
  g3w-admin/core/utils/structure.py
  g3w-admin/editing/api/base/views.py
  g3w-admin/editing/forms.py
  g3w-admin/editing/receivers.py
  g3w-admin/openrouteservice/api/views.py
  g3w-admin/openrouteservice/forms.py
  g3w-admin/openrouteservice/utils.py
  g3w-admin/qdjango/api/layers/views.py
  g3w-admin/qdjango/api/projects/serializers.py
  g3w-admin/qdjango/forms/messages.py
  g3w-admin/qdjango/forms/projects.py
  g3w-admin/qdjango/models/column_acl.py
  g3w-admin/qdjango/models/constraints.py
  g3w-admin/qdjango/models/geoconstraints.py
  g3w-admin/qdjango/models/messages.py
  g3w-admin/qdjango/models/projects.py
  g3w-admin/qdjango/models/qgisauth.py
  g3w-admin/qdjango/utils/data.py
  g3w-admin/qdjango/utils/exceptions.py
  g3w-admin/qdjango/utils/validators.py
  g3w-admin/qplotly/api/widgets/serializers.py
  g3w-admin/qplotly/models.py
  g3w-admin/qtimeseries/forms.py
  g3w-admin/usersmanage/forms.py
  g3w-admin/usersmanage/models.py
  g3w-admin/usersmanage/utils.py
  g3w-admin/usersmanage/views.py
Labels: refactoring

#748 :bug: Check for 'field', 'suggest' and 'ordering' API parameters in HTTP POST.
  g3w-admin/core/api/filters.py
  g3w-admin/qdjango/tests/data/geodata/qgis_widget_test_data.gpkg
  g3w-admin/qdjango/tests/test_api.py
Labels: bug, backport to v.3.7.x, backport to v.3.6.x

#750 Check for 'field', 'suggest' and 'ordering' API parameters in HTTP POST calls. (#748)
  g3w-admin/core/api/filters.py
  g3w-admin/qdjango/tests/test_api.py
Labels: bug

#751 Get REST API parameters from HTTP GET of POST.
  g3w-admin/core/api/base/views.py
Labels: bug

#753 Fix filter feature by selection
  g3w-admin/qdjango/tests/test_api.py
  g3w-admin/qdjango/vector.py
Labels: bug, backport to v.3.7.x

#756 :bug: Fix session filter feature by selection fo PostgreSql layers
  g3w-admin/qdjango/models/filters.py
  g3w-admin/qdjango/tests/test_api.py
  g3w-admin/qdjango/vector.py
Labels: bug, backport to v.3.7.x

#759 :bug: Fix check `request` properties
  g3w-admin/qdjango/api/projects/serializers.py
Labels: bug, backport to v.3.7.x

#763 Fix editing for pk not integer.
  g3w-admin/core/api/base/vector.py
  g3w-admin/core/utils/structure.py
Labels: bug, backport to v.3.7.x, backport to v.3.6.x
