Repository g3w-suite/g3w-admin, pull requests merged in 2024-05, with the labels that each got.

#836 Ensure absolute URL for `initConfig.baseurl` + remove `initConfig.group` property
  g3w-admin/client/api/views.py
  g3w-admin/client/tests/test_api.py
  g3w-admin/client/views.py
  g3w-admin/editing/tests/test_api.py
  g3w-admin/qplotly/tests/test_api.py
  g3w-admin/qtimeseries/tests/test_api.py
Labels: refactoring

#841 Exlude layer from TOC
  g3w-admin/client/static/client/js/app.min.js
  g3w-admin/client/static/client/js/app.min.js.map
  g3w-admin/client/tests/test_api.py
  g3w-admin/core/static/css/g3wadmin.css
  g3w-admin/core/static/dist/css/g3wadmin.min.css
  g3w-admin/qdjango/api/projects/serializers.py
  g3w-admin/qdjango/locale/de/LC_MESSAGES/djangojs.mo
  g3w-admin/qdjango/locale/it/LC_MESSAGES/django.mo
  g3w-admin/qdjango/locale/it/LC_MESSAGES/django.po
  g3w-admin/qdjango/migrations/0119_layer_exclude_from_toc.py
  g3w-admin/qdjango/migrations/0120_alter_layer_exclude_from_toc.py
  g3w-admin/qdjango/models/projects.py
  g3w-admin/qdjango/templates/qdjango/layers_list.html
  g3w-admin/qdjango/tests/test_api.py
  g3w-admin/qdjango/views/projects.py
Labels: feature

#846 Download single feature attribute in PDF format
  g3w-admin/client/static/client/js/app.min.js
  g3w-admin/client/static/client/js/app.min.js.map
Labels: feature

#850 Check for custom `G3W_PROJ4_EPSG` setting into `/crs/<epsg_code>` API response
  g3w-admin/core/api/views.py
  g3w-admin/core/tests/test_api.py
Labels: bug, backport to v.3.7.x

#845 :arrow_up: Bump g3w-client v3.9.8
  README.md
  g3w-admin/client/static/client/js/app.min.js
Labels: dependencies

#832 Add 'other_info' (userdata) to user form.
  g3w-admin/usersmanage/forms.py
  g3w-admin/usersmanage/receivers.py
  g3w-admin/usersmanage/views.py
Labels: feature

#848 Fix change project logo url
  g3w-admin/about/api/serializers.py
  g3w-admin/core/api/serializers.py
Labels: bug, backport to v.3.7.x

#844 Fix map alias url
  g3w-admin/client/views.py
Labels: bug

#809 ✨ Filter group bar
  g3w-admin/core/forms.py
  g3w-admin/core/locale/it/LC_MESSAGES/django.mo
  g3w-admin/core/locale/it/LC_MESSAGES/django.po
  g3w-admin/core/templates/core/group_list.html
  g3w-admin/core/views.py
  g3w-admin/usersmanage/locale/it/LC_MESSAGES/django.mo
  g3w-admin/usersmanage/locale/it/LC_MESSAGES/django.po
Labels: feature

#862 Download pdf attributes
  g3w-admin/base/settings/base.py
  g3w-admin/core/api/views.py
  g3w-admin/core/apiurls.py
  g3w-admin/qdjango/api/projects/serializers.py
  g3w-admin/qdjango/migrations/0121_layer_download_pdf.py
  g3w-admin/qdjango/models/projects.py
  g3w-admin/qdjango/templates/qdjango/layers_list.html
  requirements.txt
Labels: feature
