Repository g3w-suite/g3w-admin, pull requests merged in 2024-01, with the labels that each got.

#702 :bug: Fix user form list backend
  g3w-admin/usersmanage/forms.py
Labels: bug, backport_v3.6

#705 Backport fix #701
  g3w-admin/usersmanage/forms.py
Labels: bug

#704 Relation reference filters
  g3w-admin/client/static/client/js/app.min.js
  g3w-admin/core/api/base/views.py
  g3w-admin/editing/static/editing/js/plugin.js
  g3w-admin/editing/tests/test_api_transaction_group.py
  g3w-admin/qdjango/utils/edittype.py
Labels: feature

#708 Cascading relationships
  g3w-admin/client/static/client/js/app.min.js
  g3w-admin/core/api/base/views.py
  g3w-admin/editing/api/base/views.py
  g3w-admin/editing/static/editing/js/plugin.js
  g3w-admin/qdjango/vector.py
Labels: bug

#713 ⬆️ Bump g3w-client v3.9.1 and g3w-client-plugin-editing v3.7.2
  g3w-admin/client/static/client/js/app.min.js
  g3w-admin/editing/static/editing/js/plugin.js
Labels: dependencies

#711 Add 'arcgisvectortiellayer' type management.
  g3w-admin/qdjango/utils/data.py
Labels: feature

#712 Deeper relationship management for editing.
  g3w-admin/core/api/base/views.py
  g3w-admin/editing/api/base/views.py
  g3w-admin/qdjango/utils/edittype.py
  g3w-admin/qdjango/vector.py
Labels: bug

#714 Fix 'arcgisvectortilelayer' type.
  g3w-admin/qdjango/utils/data.py
Labels: feature

#717 ⬆️ Bump g3w-client-plugin-editing v3.7.3
  README.md
  g3w-admin/editing/static/editing/js/plugin.js
Labels: dependencies

#706 Add `edit_url` and `layers_url` attribute into initial client API response (ref: `group-project-map-config`)
  g3w-admin/client/tests/test_api.py
  g3w-admin/qdjango/api/projects/serializers.py
Labels: feature

#720 Invalidate cache on filter-layer-by-user saving.
  g3w-admin/qdjango/vector.py
Labels: bug, backport v.3.7.x

#718 ⬆️ Bump g3w-client v3.9.2
  README.md
  g3w-admin/client/static/client/js/app.min.js
Labels: dependencies

#721 :bug: Invalidate cache project on filter-by-user saving
  g3w-admin/qdjango/vector.py
Labels: bug
