Repository g3w-suite/g3w-admin, pull requests merged in 2024-10, with the labels that each got.

#945 ⬆️ Bump g3w-client v3.10.4
  README.md
  g3w-admin/client/static/client/js/app.min.js
  g3w-admin/client/static/client/js/app.min.js.map
Labels: dependencies

#946 Add RuleRenderer case.
  g3w-admin/qdjango/server_filters/legend/getlegendgraphic.py
Labels: bug, backport to v.3.7.x, backport to v.3.8.x

#942 Add active column to users list table
  g3w-admin/usersmanage/templates/usersmanage/user_list.html
Labels: feature

#929 Keep attribute table fields order
  g3w-admin/qdjango/tests/data/g3wsuite_project_test_qgis334.qgs
  g3w-admin/qdjango/tests/test_utils.py
  g3w-admin/qdjango/utils/data.py
Labels: feature

#949 Value relation order by value
  g3w-admin/qdjango/utils/edittype.py
Labels: feature

#951 Value relation order by value
  g3w-admin/qdjango/utils/edittype.py
Labels: bug

#953 Fix 'ghost' layer's vectorjoins management.
  g3w-admin/qdjango/utils/data.py
Labels: bug, backport to v.3.8.x

#959 Add label property to edit type checkbox.
  g3w-admin/qdjango/utils/edittype.py
Labels: feature

#957 Editing layer visible status
  g3w-admin/client/static/client/js/vendor.min.js
  g3w-admin/client/templates/client/index.html
  g3w-admin/core/utils/structure.py
  g3w-admin/editing/forms.py
  g3w-admin/editing/migrations/0013_g3weditinglayer_visible.py
  g3w-admin/editing/models/editing.py
  g3w-admin/editing/receivers.py
  g3w-admin/editing/static/editing/js/plugin.js
  g3w-admin/editing/static/editing/js/plugin.js.map
  g3w-admin/editing/static/editing/js/widget.js
  g3w-admin/editing/tests/data/api/editing_api_config_cities_54d40b01_2af8_4b17_8495_c5833485536e.json
  g3w-admin/editing/views.py
Labels: feature

#966 Set to true not_show_attributes_table layers property
  g3w-admin/qdjango/api/projects/serializers.py
Labels: bug

#965 Add geometry column to csv export vector layer.
  g3w-admin/qdjango/tests/test_api.py
  g3w-admin/qdjango/vector.py
Labels: feature

#961 Add 'autofilter' parameter management for /vector/api/data
  g3w-admin/client/static/client/css/app.min.css
  g3w-admin/client/static/client/js/vendor.min.js
  g3w-admin/client/templates/client/index.html
  g3w-admin/core/api/base/views.py
  g3w-admin/qdjango/receivers.py
  g3w-admin/qdjango/tests/test_api.py
Labels: feature
