Repository g3w-suite/g3w-admin, pull requests merged in 2025-04, with the labels that each got.

#1077 Fix ordering with fformatter field of type int float or real.
  g3w-admin/core/api/base/views.py
Labels: bug, backport to v.3.9.x

#1082 Export (download) relationship layers (#1072)
  g3w-admin/client/static/client/vendor.min.js
  g3w-admin/client/static/client/vendor.min.js.map
  g3w-admin/core/api/base/views.py
  g3w-admin/core/migrations/0084_alter_group_options_alter_macrogroup_options_and_more.py
  g3w-admin/core/tests/test_api.py
  g3w-admin/qdjango/api/constraints/filters.py
  g3w-admin/qdjango/api/layers/filters.py
  g3w-admin/qdjango/api/projects/serializers.py
  g3w-admin/qdjango/auth.py
  g3w-admin/qdjango/models/projects.py
  g3w-admin/qdjango/templates/qdjango/project_list.html
  g3w-admin/qdjango/tests/data/g3wsuite_project_test_qgis340.qgs
  g3w-admin/qdjango/tests/test_api.py
  g3w-admin/qdjango/vector.py
  g3w-admin/qplotly/utils/qplotly_factory.py
Labels: feature

#1079 ⬆️ Bump g3w-client v3.11.7
  README.md
  g3w-admin/client/static/client/app.min.css
  g3w-admin/client/static/client/app.min.js
  g3w-admin/client/static/client/app.min.js.map
  g3w-admin/client/static/client/vendor.min.js
  g3w-admin/client/static/client/vendor.min.js.map
Labels: dependencies

#1087 Update runs-on github action image version
  .github/workflows/deploy_dev_g3wsuite.yml
  .github/workflows/test_runner.yml
Labels: dependencies, continue integration

#1086 ⬆️ Bump g3w-client v3.11.8 - g3w-client-plugin-qplotly v3.9.1
  README.md
  g3w-admin/client/static/client/app.min.css
  g3w-admin/client/static/client/app.min.js
  g3w-admin/client/static/client/app.min.js.map
  g3w-admin/qplotly/static/qplotly/js/plugin.js
  g3w-admin/qplotly/static/qplotly/js/plugin.js.map
Labels: dependencies

#1089 Case 'autofilter=1' with zero results.
  g3w-admin/core/api/base/views.py
  g3w-admin/qdjango/receivers.py
  g3w-admin/qdjango/vector.py
Labels: bug, backport to v.3.9.x
