Repository g3w-suite/g3w-admin, pull requests merged in 2025-01, with the labels that each got.

#1005 Fix media update
  g3w-admin/core/utils/vector.py
Labels: bug

#1004 Update to Django 4.2
  README.md
  docker-compose.latest.yml
  docker-compose.ltr.yml
  g3w-admin/about/tests/test_api.py
  g3w-admin/base/__init__.py
  g3w-admin/base/management/commands/set_passwords.py
  g3w-admin/base/settings/base.py
  g3w-admin/caching/views.py
  g3w-admin/core/api/base/views.py
  g3w-admin/core/forms.py
  g3w-admin/core/mixins/views.py
  g3w-admin/core/models.py
  g3w-admin/core/signals.py
  g3w-admin/core/tests/test_api.py
  g3w-admin/core/utils/data.py
  g3w-admin/core/utils/forms.py
  g3w-admin/core/utils/request.py
  g3w-admin/core/utils/response.py
  g3w-admin/core/utils/structure.py
  g3w-admin/editing/tests/data/editing_test_qgis310.qgs
  g3w-admin/editing/tests/data/editing_test_qgis334.qgs
  g3w-admin/editing/tests/test_models.py
  g3w-admin/filemanager/filemanager.py
  g3w-admin/openrouteservice/tests/test_api.py
  g3w-admin/qdjango/forms/projects.py
  g3w-admin/qdjango/models/messages.py
  g3w-admin/qdjango/signals.py
  g3w-admin/qdjango/tests/base.py
  g3w-admin/qdjango/tests/data/geodata/qgis_widget_test_data.gpkg
  g3w-admin/qdjango/tests/test_accesscontrol.py
  g3w-admin/qdjango/tests/test_api.py
  g3w-admin/qdjango/tests/test_app.py
  g3w-admin/qdjango/tests/test_column_acl.py
  g3w-admin/qdjango/tests/test_constraints.py
  g3w-admin/qdjango/tests/test_embedded_layers.py
  g3w-admin/qdjango/tests/test_ows.py
  g3w-admin/qdjango/tests/test_ows_postgres.py
  g3w-admin/qdjango/tests/test_qgisauth.py
  g3w-admin/qdjango/tests/test_styles_api.py
  g3w-admin/qdjango/tests/test_theme.py
  g3w-admin/qdjango/tests/test_utils.py
  g3w-admin/qdjango/tests/test_validators.py
  g3w-admin/qdjango/utils/data.py
  g3w-admin/qdjango/utils/exceptions.py
  g3w-admin/qdjango/utils/validators.py
  g3w-admin/qplotly/tests/test_api.py
  g3w-admin/qplotly/tests/test_models.py
  g3w-admin/qplotly/tests/test_views.py
  g3w-admin/qtimeseries/tests/base.py
  g3w-admin/usersmanage/forms.py
  g3w-admin/usersmanage/signals.py
  g3w-admin/usersmanage/tests/test_api.py
  g3w-admin/usersmanage/tests/test_utils.py
  g3w-admin/usersmanage/utils.py
  requirements.txt
  settings_docker.py
Labels: dependencies, refactoring, python

#1012 Fix upload file on fielmanager
  g3w-admin/base/settings/base.py
  g3w-admin/core/static/css/g3wadmin.css
  g3w-admin/core/static/dist/css/g3wadmin.min.css
  g3w-admin/filemanager/filemanager.py
  g3w-admin/filemanager/utils/__init__.py
  g3w-admin/filemanager/utils/storage.py
  g3w-admin/qdjango/utils/storage.py
Labels: bug, backport to v.3.9.x

#1016 Fix update user data
  g3w-admin/templates/bootstrap3/layout/prepended_appended_text.html
  g3w-admin/usersmanage/forms.py
Labels: bug, backport to v.3.9.x

#1014 ⬆️ Bump g3w-client v3.11.1
  README.md
  g3w-admin/client/static/client/app.min.js
  g3w-admin/client/static/client/app.min.js.map
  g3w-admin/client/static/client/vendor.min.js.map
Labels: bug

#1019 Fix save and update user
  g3w-admin/usersmanage/forms.py
  g3w-admin/usersmanage/tests/test_forms.py
Labels: bug, backport to v.3.9.x

#1023 Add `django_filters` to setting.THIRD_PARTY_APPS
  g3w-admin/base/settings/base.py
Labels: feature

#1025 ALLOWED_HOSTS must be an array
  g3w-admin/base/settings/local_settings_example.py
Labels: bug, backport to v.3.9.x

#1007 ⬆️ Bump g3w-client v3.10.8, g3w-client-plugin-editing v3.8.5
  README.md
  g3w-admin/client/static/client/js/app.min.js
  g3w-admin/client/static/client/js/app.min.js.map
  g3w-admin/editing/static/editing/js/plugin.js
Labels: dependencies
