Repository g3w-suite/g3w-admin, pull requests merged in 2025-05, with the labels that each got.

#1095 Invalidate project api config cache on create/update custom theme
  g3w-admin/qdjango/api/projects/serializers.py
  g3w-admin/qdjango/api/projects/views.py
Labels: bug, backport to v.3.9.x

#1097 Fix rule key when SHOWFEATURECOUNT is true
  g3w-admin/qdjango/server_filters/legend/getlegendgraphic.py
Labels: bug, backport to v.3.9.x

#1090 ⬆️ Bump g3w-client v3.11.9 and g3w-client-plugin-editing v3.9.2
  README.md
  g3w-admin/client/static/client/app.min.js
  g3w-admin/client/static/client/app.min.js.map
  g3w-admin/client/static/client/vendor.min.js
  g3w-admin/client/static/client/vendor.min.js.map
  g3w-admin/editing/static/editing/js/plugin.js
  g3w-admin/editing/static/editing/js/plugin.js.map
Labels: dependencies

#1106 Set attribute idx for QgsFeatureRequest for autofilter = 1
  g3w-admin/core/api/base/views.py
Labels: bug, backport to v.3.9.x

#1115 Qplotly widgets ordering
  g3w-admin/qplotly/admin.py
  g3w-admin/qplotly/apiurls.py
  g3w-admin/qplotly/migrations/0006_alter_qplotlywidget_options_qplotlywidget_order.py
  g3w-admin/qplotly/migrations/0007_alter_qplotlywidget_options_and_more.py
  g3w-admin/qplotly/migrations/0008_alter_qplotlywidget_order.py
  g3w-admin/qplotly/models.py
  g3w-admin/qplotly/receivers.py
  g3w-admin/qplotly/templates/qplotly/plots_list_order.html
  g3w-admin/qplotly/templates/qplotly/plots_list_order_action.html
  g3w-admin/qplotly/urls.py
  g3w-admin/qplotly/utils/models.py
  g3w-admin/qplotly/views.py
Labels: feature

#1119 Fix natural sorting
  g3w-admin/core/api/base/views.py
  requirements.txt
Labels: bug, backport to v.3.9.x

#1113 Customizable layer visibility constraints (per user/group + min/max scale)
  g3w-admin/core/static/components/data-widget-scalevisconstraintManagerList.js
  g3w-admin/qdjango/admin.py
  g3w-admin/qdjango/api/layerscaleconstraints/__init__.py
  g3w-admin/qdjango/api/layerscaleconstraints/permissions.py
  g3w-admin/qdjango/api/layerscaleconstraints/serializers.py
  g3w-admin/qdjango/api/layerscaleconstraints/views.py
  g3w-admin/qdjango/api/projects/serializers.py
  g3w-admin/qdjango/apiurls.py
  g3w-admin/qdjango/migrations/0124_alter_project_show_metadata_section.py
  g3w-admin/qdjango/migrations/0125_scalevisibilitylayerconstraint.py
  g3w-admin/qdjango/migrations/0126_scalevisibilitylayerconstraint_layer_user_unique_and_more.py
  g3w-admin/qdjango/migrations/0127_alter_scalevisibilitylayerconstraint_options_and_more.py
  g3w-admin/qdjango/models/__init__.py
  g3w-admin/qdjango/models/layerscaleconstraints.py
  g3w-admin/qdjango/models/projects.py
  g3w-admin/qdjango/receivers.py
  g3w-admin/qdjango/static/qdjango/js/widget.js
  g3w-admin/qdjango/templates/qdjango/layers_list.html
  g3w-admin/qdjango/tests/test_scalevisibilitylayerconstraint.py
Labels: feature

#1124 Scale layer visibility per user 2
  g3w-admin/qdjango/api/projects/serializers.py
  g3w-admin/qdjango/models/projects.py
  g3w-admin/qdjango/server_filters/accesscontrol/scalevisibilitylayerconstraint.py
  g3w-admin/qdjango/tests/data/g3wsuite_project_test_qgis340_3857.qgs
  g3w-admin/qdjango/tests/test_constraints.py
  g3w-admin/qdjango/tests/test_scalevisibilitylayerconstraint.py
Labels: feature

#1110 ⬆️ Bump g3w-client v3.11.11
  README.md
  g3w-admin/client/static/client/app.min.js
  g3w-admin/client/static/client/app.min.js.map
Labels: dependencies

#1094 Add IN operator to widget search options
  g3w-admin/client/static/client/app.min.css
  g3w-admin/client/static/client/app.min.css.map
  g3w-admin/core/api/filters.py
  g3w-admin/qdjango/static/qdjango/js/widget.js
  g3w-admin/qdjango/tests/test_api.py
Labels: feature
