Repository g3w-suite/g3w-admin, pull requests merged in 2025-02, with the labels that each got.

#1031 Fix place hold project image
  g3w-admin/base/settings/base.py
  g3w-admin/qdjango/templates/qdjango/project_list.html
Labels: bug, backport to v.3.9.x

#1028 ⬆️ Bump g3w-client v3.11.2
  README.md
  g3w-admin/client/static/client/app.min.js
  g3w-admin/client/static/client/app.min.js.map
  g3w-admin/client/static/client/fonts/titillium-web-latin-400-italic.woff2
  g3w-admin/client/static/client/fonts/titillium-web-latin-400-normal.woff2
  g3w-admin/client/static/client/fonts/titillium-web-latin-700-italic.woff2
  g3w-admin/client/static/client/fonts/titillium-web-latin-700-normal.woff2
  g3w-admin/client/static/client/fonts/titillium-web-latin-ext-400-italic.woff2
  g3w-admin/client/static/client/fonts/titillium-web-latin-ext-400-normal.woff2
  g3w-admin/client/static/client/fonts/titillium-web-latin-ext-700-italic.woff2
  g3w-admin/client/static/client/fonts/titillium-web-latin-ext-700-normal.woff2
  g3w-admin/client/static/client/vendor.min.js.map
Labels: dependencies

#1040 Update 'sitetrees' modules
  g3w-admin/core/sitetrees.py
  g3w-admin/filemanager/sitetrees.py
  g3w-admin/openrouteservice/sitetrees.py
  g3w-admin/qdjango/sitetrees.py
  g3w-admin/usersmanage/sitetrees.py
Labels: bug, backport to v.3.9.x

#1034 :arrow_up: g3w-client v3.11.3
  README.md
  g3w-admin/client/static/client/app.min.js
  g3w-admin/client/static/client/app.min.js.map
  g3w-admin/client/static/client/vendor.min.js.map
Labels: dependencies

#1041 Update 'sitetrees' modules + german
  g3w-admin/core/sitetrees.py
  g3w-admin/filemanager/sitetrees.py
  g3w-admin/openrouteservice/sitetrees.py
  g3w-admin/openrouteservice/urls.py
  g3w-admin/usersmanage/sitetrees.py
Labels: ux, i18n, backport to v.3.9.x

#1050 ⬆️ Bump g3w-client v3.11.4
  README.md
  g3w-admin/client/static/client/app.min.js
  g3w-admin/client/static/client/app.min.js.map
Labels: dependencies

#1053 Add ACL to api/config 'relations' section
  g3w-admin/client/tests/test_api.py
  g3w-admin/qdjango/api/projects/serializers.py
  g3w-admin/qplotly/receivers.py
  g3w-admin/qplotly/tests/test_api.py
Labels: bug, backport to v.3.9.x

#1057 ⬆️ Bump g3w-client v3.11.5 and g3w-client-plugin-editing v3.9.1
  README.md
  g3w-admin/client/static/client/app.min.js
  g3w-admin/client/static/client/app.min.js.map
  g3w-admin/editing/static/editing/js/plugin.js
  g3w-admin/editing/static/editing/js/plugin.js.map
Labels: dependencies
