Repository g3w-suite/g3w-admin, pull requests merged in 2025-07, with the labels that each got.

#1150 Fix "Translatable fields" string being untranslatable
  g3w-admin/core/forms.py
  g3w-admin/qdjango/forms/projects.py
Labels: bug, backport to v.3.9.x

#1158 Translate `G3WUserForm` fields for department, backend and avatar
  g3w-admin/usersmanage/forms.py
Labels: bug, i18n, backport to v.3.9.x

#1157 Make UTF compatible symbol in the creative commons license file
  g3w-admin/qdjango/tests/data/geodata/Creative_Commons_Legal_Code.txt
Labels: bug, backport to v.3.9.x

#1156 Make footer fully translatable
  g3w-admin/templates/base.html
Labels: i18n, backport to v.3.9.x

#1167 Make the "permanently delete" label clickable to toggle the checkbox
  g3w-admin/core/static/js/g3wadmin/widget.js
Labels: feature

#1171 ⬆️ Bump g3w-client v3.11.14
  g3w-admin/client/static/client/app.min.js
  g3w-admin/client/static/client/app.min.js.map
Labels: dependencies

#1173 Qes (Elasticsearch module) commands and Huey cronjob-like tasks
  g3w-admin/qes/management/__init__.py
  g3w-admin/qes/management/commands/__init__.py
  g3w-admin/qes/management/commands/qes_indexer.py
  g3w-admin/qes/receivers.py
  g3w-admin/qes/tasks.py
  g3w-admin/qes/utils/__init__.py
Labels: feature
